---
title: 'All countries with over 100 cases (alphabetical order)'
output: html_document
---

```{r libraries, echo = F, message = F, warning = F, results='hide'}
library(lubridate, warn.conflicts = F)
library(plotly, warn.conflicts = F)
library(ggplot2, warn.conflicts = F)
library(magrittr, warn.conflicts = F)
library(dplyr, warn.conflicts = F)
Sys.setlocale('LC_TIME', 'C')
source("plot.r")
source("estimator.r")
```

```{r data, echo = F}
johns_hopkins <- read.csv("data/clean/data_world_jh.csv")
```

```{r plots, echo = F, cache = F, message = F}

```

## {.tabset .tabset-fade}

[back](index.html)

<!--
See https://github.com/rstudio/flexdashboard/issues/80#issuecomment-247139450
on generating tabs in rmarkdown automatically
-->
```{r, echo = F, warning = F, message = F}

maxday <- max(johns_hopkins$day)
df <- subset(johns_hopkins, day == maxday, select = c(reg0.name, tot.cases))
df <- df[order(df$reg0.name),]
countries <- df$reg0.name[df$tot.cases > 100]
names(countries) <- countries

plots <- lapply(countries, function(country_name) {
    country <- johns_hopkins %>%
        filter(reg0.name == country_name) %>%
        mutate(date = ymd(date))

    estimates <- cbind(country, repronum(
            new.cases = country$new.cases,
            profile = infectivity,
            window = width,
            delay = report.delay,
            conf.level = 1 - alpha,
            pad.zeros = TRUE
        ))
    
    plot_repronum(estimates, country_name, language = "en")
})

out <- lapply(seq_along(plots), function(i) {

  a1 <- knitr::knit_expand(text = sprintf("### %s\n", countries[i])) # tab header, auto extracts names of `hcs`
  a2 <- knitr::knit_expand(text = "\n```{r, echo = F, fig.width = 10}") # start r chunk
  a3 <- knitr::knit_expand(text = sprintf("\nplots[[%d]]", i)) # extract graphs by "writing" out `hcs[[1]]`, `hcs[[2]]` etc. to be rendered later
  a4 <- knitr::knit_expand(text = "\n```\n") # end r chunk

  paste(a1, a2, a3, a4, collapse = '\n') # collapse together all lines with newline separator
})
```

`r paste(knitr::knit(text = paste(out, collapse = '\n')))`
